version: 1

# Checkmarx configuration file
#
# https://checkmarx.com/resource/documents/en/34965-68549-configuring-projects-using-config-as-code-files.html
checkmarx:
  scan:
    configs:
      sast:
        presetName: "BW ASA Premium"
        # Exclude spec files, and test specific files
        filter: "!*.spec.ts,!**/spec/**,!apps/desktop/native-messaging-test-runner/**"
